services:
  - type: web
    name: family-budget
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: npm install && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
